---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - golem.spot-os.io
  resources:
  - spotinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - golem.spot-os.io
  resources:
  - spotinstances/finalizers
  verbs:
  - update
- apiGroups:
  - golem.spot-os.io
  resources:
  - spotinstances/status
  verbs:
  - get
  - patch
  - update
